### ISSUE TITLE
Firmware build fails when no PYTHONPATH and PYTHONHOME is set

### ISSUE THREAD

**Issue by maxbab1** [SiLab-Bonn/tj-monopix2-daq#4]
Appearently the run.tcl file just unsets it, but if there is nothing to unset it fails

**Comment by themperek** [comment]
I am not sure but I this may have something to do with vivado version.

**Comment by ChristianBesp** [comment]
Which vivado version one are you using? Vivado usually ships it's own python interpreter which we do not want to use since the packages (like basil, which we depend on in the .tcl file) are not installed there. This is the reason why it is unset from the environment to use the standard python interpreter in the current PATH.
Unfortunately, this behavior of vivado changes throughout their versions.

Firmware compilation is tested with vivado 2019.2 on my end.

**Comment by DavidLP** [comment]
One could just check it before: https://stackoverflow.com/questions/37085392/tcl-how-to-check-if-environment-variable-already-set

**Comment by ChristianBesp** [comment]
But you still need to make sure that you are using the correct python interpreter. Pull-requests are always welcome if someone manages to make it work with more vivado versions

**Comment by maxbab1** [comment]
oh, i am using 2018.2, as it was recommended in the cern repo... also the building fails now, so i will try to install 2019.2

**Comment by ChristianBesp** [comment]
With every release Vivado included changes related to python from its TCL shell. Compiling should be supported for Vivado 2018 to 2021 with a7073bffc6469b01d4f9073a936a76152cb258ad. Otherwise feel free to reopen.
